name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # If you have a requirements.txt file for Python dependencies
        # Or install any other dependencies your project needs

    - name: Run unit tests
      run: |
        pytest  # Modify this command to run your unit tests for your chosen language and framework
