name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
       ref: assignment 1
       sub modules: recursive
      

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  
    - name: Install dependencies
      run: |
        pip install pytest  

    - name: Run unit tests
      run: |
        pytest unitcalculator.py
